#! /bin/bash

#version 0.3   09.05.09 -- initial version
#version 0.4   14.08.09 -- better version + --viewer

usage="Usage: ${0##*/} script <script2> ..."
viewer=${0##*/f}
viewer="$(type -p ${viewer:-less})"

help () {
  cat << eof
Show content of file after readlink
$usage
OPTIONS:
-v, --viewer CMD Change the viewer
                 Default: $viewer
-h, --help       Show this help
-v, --version    Show version

Examples:  ${0##*/} egrep 
           ${0##*/} dvipdf egrep
           ${0##*/} dvipdf | less

Send bugs and comment to junghans@mpip-mainz.mpg.de
eof
}

while [ "${1#-}" != "$1" ]; do
 case $1 in
   -v | --viewer)
    viewer="$2"
    shift 2;; 
   -h | --help)
    help
    exit 0;;
   --hg)
    echo "${0##*/}: $(sed -ne 's/^#version.* -- \(.*$\)/\1/p' $0 | sed -n '$p')"
    exit 0;;
   -v | --version)
    echo "${0##*/}", $(sed -ne 's/^#\(version.*\) -- .*$/\1/p' $0 | sed -n '$p') by C. Junghans
    exit 0;;
  *)
   echo "Unknown option '$1' - ignored" >&2
   exit 1 ;;
 esac
done

if [ -z "$1" ]; then
  echo $usage
  echo Help with -h
  exit 1
fi

if [ -z "$viewer" ]; then
  echo NO vim found, use --viewer option >&2
  exit 1
fi

for i in $*; do
  name=$(readlink -f $(type -p $i))
  if [ -z "$name" ]; then
   echo "'$i' not found, try 'type $i'!"
   echo "(because you are in a interactive shell)!"
   exit
 else
   $viewer $name
  fi
done

