#! /bin/bash

die() {
  echo "$*" >&2
  exit 1
}

[[ -t 1 ]] && color="always" || color="never"

[[ -z $1 || -z $2 ]] && die "Missing argument"
find . -name "${!#}" -type f -exec grep --color="$color" -nHE "${@:1:$#-1}" {} + | sed 's/:/ :/'
