#! /bin/bash

#version 0.1e 27.06.08 -- initial version
#version 0.1f 16.04.08 -- better verion system
#version 0.2  01.10.08 -- added readlink in the name
VIM=vim70
usage="Usage: ${0##*/} script <script2> ..."

help () {
  cat << eof
Edit (with vim) content of file after readlink
$usage
OPTIONS:
-h, --help      Show this help
-v, --version   Show version

Examples:  ${0##*/} egrep 
           ${0##*/} dvipdf egrep

Send bugs and comment to junghans@mpip-mainz.mpg.de
eof
}

while [ "${1#-}" != "$1" ]; do
 case $1 in 
   -h | --help)
    help
    exit 0;;
   -v | --version)
    echo "${0##*/}", $(sed -ne 's/^#\(version.*\) -- .*$/\1/p' $0 | sed -n '$p') by C. Junghans
    exit 0;;
  *)
   echo Unknown option \'$1\' - ignored
   shift ;;
 esac
done

if [ -z "$1" ]; then
	echo 
  echo Usage: ${0##*/} scriptname
  exit
fi

for i in $*; do
 name=$(readlink -f $(type -p $i))
 if [ -z "$name" ]; then
  echo \"$i\" not found, try \"type $i\"!
  echo \(because you are in a interactive shell\)!
  exit
 else
  if [ -z "$(file -L $name | grep 'executable')" ]; then
   $VIM $name
  else
   echo $i is a binary
  fi
 fi
done

