#! /bin/bash
#C. Junghans
#This script was motivated by Thomas Kahle (www.pi-ist-genau-3.de)
#who has a guard script of his friend Georg, which was much to 
#complikated for me !

#version 0.9  19.09.07 -- added --xpdf
#version 0.10 10.10.07 -- allowing short opts
#version 0.11 18.10.07 -- remove string bug in short opts
#version 0.12 06.02.08 -- remove base name
#version 0.13 06.03.08 -- add --self
#version 0.14 16.04.08 -- better version system
#version 0.2  04.06.12 -- major clean up

usage="Usage: ${0##*/} file1 <file2> ..."
runcom="make"
quiet="no"
waittime=3

die() {
  echo -e "$*" >&2
  exit 1
}

help () {
  cat << eof
Run a command if file is changed
$usage
OPTIONS:
-e, --exec COMMAND  Run the command COMMAND
                    Default: $runcom
-t, --time SEC      Wait SEC secs until run command
                    Default: $waittime
-s, --self          Add first file to command
-q, --quiet         Be a little bit quiet
-h, --help          Show this help
-v, --version       Show version

Examples:  ${0##*/} bla.tex
           ${0##*/} -e "make -f other_makefile" some_file
           ${0##*/} -e "povray +A -W800 -H600 file.pov" file.pov

Send bugs and comment to junghans@mpip-mainz.mpg.de
eof
}

while [ "${1#-}" != "$1" ]; do
 if [ "${1#--}" = "$1" ] && [ -n "${1:2}" ]; then
    if [ "${1#-[et]}" != "${1}" ]; then
       set -- "${1:0:2}" "${1:2}" "${@:2}"
    else
       set -- "${1:0:2}" "-${1:2}" "${@:2}"
    fi
 fi
 case $1 in 
   -e | --exec)
    runcom=$2
    shift 2;;
   -t | --time)
    waittime=$2
    [[ $waittime -gt 0 ]] || die "Argument of -t should be int and bigger than 0"
    shift 2;;
   -q | --quiet)
    quiet="yes"
    shift ;;
   -s | --self)
    self="yes"
    shift ;;
   -h | --help)
    help
    exit 0;;
   --hg)
    echo "${0##*/}: $(sed -ne 's/^#version.* -- \(.*$\)/\1/p' $0 | sed -n '$p')"
    exit 0;;
   -v | --version)
    echo "${0##*/}", $(sed -ne 's/^#\(version.*\) -- .*$/\1/p' $0 | sed -n '$p') by C. Junghans
    exit 0;;
  *)
   die "Unknown option '$1'"
   shift ;;
 esac
done

[[ -z $1 ]] && die "No file given !\n$usage\nHelp with -h"

[[ $self = yes ]] && runcom="$runcom $1"

i=0
for f in "$@"; do
  filename[$i]=$f
  [[ -f $f ]] || die "$f not found or readable"
  checksum[$i]=$(sha1sum $f)
  (( i++ ))
done

echo "Guarding files ${filename[*]}"
echo "for doing '$runcom' every $waittime secs"

$runcom

echo ${0##*/} is waiting...  
while true; do
  sleep $waittime
  run="no"
  [[ "$quiet" = "no" ]] && echo "${0##*/} is waiting..."
  for (( i=0;i<${#filename[*]};i++)); do
    newchecksum=$(sha1sum ${filename[$i]})
    if [[ $newchecksum != ${checksum[$i]} ]]; then
      echo "'${filename[$i]}' has changed!"
      checksum[$i]=$newchecksum
      run="yes"
    fi
  done
  if [[ $run = yes ]]; then
    $runcom
    echo ${0##*/} is waiting...
  fi
done
