#! /bin/bash

host="junghans@login.mpip-mainz.mpg.de"
repobase="hgrepos"

if [ -z "$1" ]; then
   $0 --help
   exit 0
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   cat <<EOF
Usage: ${0##*/} file 

This is wrapper to commit a file with msg \$(file --hg).

EOF
   exit 0
fi

if [ ! -f "$1" ]; then
   echo File \"$1\" is not readable
   exit 1
fi

msg=$(./$1 --hg)
[[ $? -eq 0 ]] || { echo Could not get commit message; exit 1; }

[[ -n "$msg" ]] || { echo Empty commit message; exit 1; }

echo Msg: \"$msg\"
hg commit -m "$msg" $1
[[ $? -eq 0 ]] || { echo Error at running hg; exit 1; }
