#! /bin/bash

diff=tkdiff

if [ -z "$1" ]; then
   ${0##*/} --help
   exit 0
fi

if [ "$1" == "--help" ]; then
   echo Usage: ${0##*/} [hg-options] file
   echo See hg-option with hg diff --help
   echo Version 0.2 - 24.09.08
   exit 0
fi

filename=$(hg diff $* | awk '(NR==1){print $4}')
if [ -z "$filename" ]; then
   echo Error: empty patch \(file not found or changes\)
   exit 1
fi

if [ ! -r $filename ]; then
   echo Error: File \"$filename\" not found
   exit 1
fi

TMPFILE=$(mktemp)
cp $filename $TMPFILE
hg diff $* | patch -s -R $TMPFILE
if [ $? -ne 0 ]; then
   echo Error: Could not apply patch
   rm $TMPFILE
   exit 1
fi

$diff -L "$filename (HG)" -L "$filename (local)" $TMPFILE $filename 
rm $TMPFILE
