#! /bin/bash

host="junghans@login.mpip-mainz.mpg.de"
repobase="hgrepos"

if [ -z "$1" ]; then
   $0 --help
   exit 0
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   cat <<EOF
Usage: ${0##*/} push|pull|clone [name]

This is wrapper to push or pull hg repo to ${host##*@}
with login ${host%%@*}.
EOF
   exit 0
fi

if [ "$1" = "cloneto" ]; then
   op="clone ."
else
   op=$1
fi

if [ "$op" = "clone" ]; then
   [[ -n "$2" ]] || { echo clone needs a name; exit 1; }
else
   path=$(hg root)
   [[ $? -eq 0 ]] || exit 1
   cd $path
fi
  
if [ -n "$2" ]; then
   name=$2
else
   name=${path##*/}
fi
   
echo Reponame: $name
echo Operation: $1

hg $op ssh://$host/$repobase/$name
