#! /bin/bash -i

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   cat <<EOF
Usage: ${0##*/} pattern

It greps the pattern from history

Examples: ${0##*/} hg
          ${0##*/} '.' | sed 's/^[0-9]*//'
EOF
   exit 0
fi

if [ -z "$1" ]; then
   echo Error ${0##*/} needs at least 1 arguments >&2
   echo Help with ${0##*/} -h >&2
   exit 1
fi

cat $HISTFILE | grep --color=auto -aEe "$@"
