#! /bin/bash
#C. Junghans

#version 0.1  05.10.08 -- initial version

usage="Usage: ${0##*/} dir dir2 .."
quiet="no"
rm_opt="-v"

help () {
  cat << eof
Remove broken links in a dir
$usage
OPTIONS:
-i                  Ask before remove
-q, --quiet         Be a little bit quiet
-h, --help          Show this help
-v, --version       Show version

Examples:  ${0##*/} . 
           ${0##*/} -q \$HOME

Send bugs and comment to junghans@mpip-mainz.mpg.de
eof
}

while [ "${1#-}" != "$1" ]; do
 if [ "${1#--}" = "$1" ] && [ -n "${1:2}" ]; then
    if [ "${1#-[et]}" != "${1}" ]; then
       set -- "${1:0:2}" "${1:2}" "${@:2}"
    else
       set -- "${1:0:2}" "-${1:2}" "${@:2}"
    fi
 fi
 case $1 in 
   -i)
    rm_opt="$rm_opt -i"
    shift ;;
   -q | --quiet)
    rm_opt=${rm_opt/-v/}
    shift ;;
   -h | --help)
    help
    exit 0;;
   --hg)
    echo "${0##*/}: $(sed -ne 's/^#version.* -- \(.*$\)/\1/p' $0 | sed -n '$p')" 
    exit 0;;
   -v | --version)
    echo "${0##*/}", $(sed -ne 's/^#\(version.*\) -- .*$/\1/p' $0 | sed -n '$p') by C. Junghans
    exit 0;;
  *)
   echo Unknown option \'$1\' 
   exit 1;;
 esac
done

if [ -z "$1" ]; then
  echo No dir given !
  echo $usage
  echo Help with -h
  exit 1
fi

for mydir in $*; do
   [[ -d $mydir ]] || { echo $mydir is not a dir >&2; exit 1; }
   find -L $mydir -type l -exec rm $rm_opt {} \;
done
